name: GitHub Actions Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: use node
      uses: actions/setup-node@v2
      with:
          node-version: 16 # node版本
    - name: install and build
      run: |
         yarn install
         yarn docs:build
    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.7
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages
        FOLDER: docs/.vuepress/dist
        BUILD_SCRIPT: yarn install && yarn docs:build
